Add relationship support and full community mapper list
collectionspace/cspace-batch-import pull request #23
Opened 2021-03-10 21:15 UTC by kspurgin

2021-03-16 17:42 UTC, mark-cooper requested changes
Hey Kristina,

Looks good. Don't worry about this right now but I'm going to add Rubocop style checks soon to enforce consistency with layout / formatting. Passing those checks will be required to have an approved PR (most code editors have a Rubocop plugin available).

There's also a broken test to do with the update for mappers, but that's an easy fix I'll do after merging.

Couple of things I'd like to see:

- Only one class per file. RecordActionChecker (and friends) should be separate.
- Service classes are usually pretty easy to test and should have them. If you just want to add placeholder files for now that's ok (tests/services), we can get to them later.
- You know this better than I do at this point -- delete any services (and things in general) that are obviously not being used (like TermManagerService and corresponding tests).

That's it 👍

2021-03-17 23:39 UTC, kspurgin commented on config/environments/test.rb
> +  config.action_controller.perform_caching = true
@mark-cooper -- was not sure how to test a service class like `RecordCacheService` with the existing settings here.

2021-03-17 23:45 UTC, kspurgin commented on test/services/step_manager_service_test.rb
>  class StepManagerServiceTest < ActiveSupport::TestCase
@mark-cooper I added some tests here for public methods that I had added (and some behavior I changed). But a fair amount of the mess I added in here manipulates CSVs behind the scenes to generate the final report for each step without storing individual CSV row data in the database or caching it. Testing this stuff requires actual data in an input CSV associated with a batch, and the ability to verify the resulting CSV(s) are as expected in the tests. The fixtures as currently set up don't seem to support testing this and I was unable to figure out how to fix that today.

2021-03-18 18:48 UTC, kspurgin commented on config/environments/test.rb
> +  config.action_controller.perform_caching = true
Figured this out...

2021-03-18 18:56 UTC, kspurgin commented
@mark-cooper - ok, I have done the following: 
- moved classes into their own files (think I meant to do that after verifying that they worked, and forgot)
- written tests for services where I could figure out how; made placeholders otherwise
- removed unused services
- various other cleanup/improvement noticed while working on the above (decoupling things to ease testing, etc.)

2021-03-30 17:28 UTC, mark-cooper approved these changes

2021-03-30 17:28 UTC, merged